import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import CardHome from "@/Components/CardHome";

const inter = Inter({ subsets: ["latin"] });
const dataCards = [
  {
    title: "Lisez les articles",
    description: "Maximisez votre culture web",
    content:
      "Chaque auteur tente de vous apporter le plus de valeur possible par article.",
    link: "/blog",
    linkText: "Visite le blog",
  },
  {
    title: "Faites un tour vers la liste de membres",
    description: "Faites-vous des amis",
    content: "Ajoutez, invitez et discutez avec les différents membres.",
    link: "/list",
    linkText: "Découvre la liste de membres",
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Next Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container__home}>
        <div>
          <h1>Bienvenue sur Code.io</h1>
          <h2>TESTSET</h2>
          <span>
            Le blog communautaire des afficionados de développement web.
          </span>
        </div>
        <div className={styles.wrapper__cards}>
          {dataCards.map((card) => (
            <CardHome data={card} />
          ))}
        </div>
      </main>
    </>
  );
}
